export const examples = [
  {
    name: 'Charity fun run after party',
    description: 'Run for the charity',
    date: '2022-05-07T12:18:00.000Z',
    location: 'Offaly',
    image: 'qwer',
    price: 10,
    capacity: 100,
    organizer: 'Downsyndrome ireland ',
    email: 'michaelnorman4421@gmail.com',
  },
  {
    name: 'Lip sync battle',
    description: 'Come watch XYZ club battle it out in the lip sync arena',
    date: '2022-05-07T12:18:00.000Z',
    location: 'Birr',
    image: 'qwer',
    price: 10,
    capacity: 500,
    organizer: 'Birr GAA Club',
    email: 'michaelnorman4421@gmail.com',
  },
  {
    name: 'Paddys Day Club session',
    description: 'Late night party for the Paddys Day',
    date: '2022-05-07T12:18:00.000Z',
    location: 'Tullamore',
    image: 'qwer',
    price: 15,
    capacity: 200,
    organizer: 'Club38',
    email: 'michaelnorman4421@gmail.com',
  },
  {
    name: 'Rugby club bake sale',
    description: 'Get some delicious cakes ',
    date: '2022-05-07T12:18:00.000Z',
    location: 'Tullamore',
    image: 'qwer',
    price: 0,
    capacity: 100,
    organizer: 'Tullamore Rugby Club',
    email: 'michaelnorman4421@gmail.com',
  },
];
